name: CI

# Controla quando o workflow inicia
on:
  # O workflow é ativado quando ha um push na branch main
  push:
    branches: [ "main" ]
  # Permite rodar o workflow da aba de Actions
  workflow_dispatch:

# Workflow composta de um ou mais jobs que podem rodar em paralelo
jobs:
  build: # Job - Build
    # O que vai rodar o job
    runs-on: ubuntu-latest

    # Steps representam uma sequencia de tarefas que serão realizadas como parte do job
    steps:
      # Checkout: Baixa o código do repositório
      - name: Baixar Repo
        uses: actions/checkout@v4

      # Configura o ambiente Node.js
      - name: Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      # Instalação: Baixa as dependências
      - name: Instalar dependencias
        run: npm install

      # Executa o linter para verificar padrões de código
      - name: Rodar Linter/Formatador
        run: npm run lint

      # Executa os testes automatizados
      - name: Rodar testes unitarios e de integração
        run: npm test

      # Cria artefato final
      - name: Compilar Aplicação
        run: npm run build

      # Salva o resultado do build para ser usado no CD
      - name: Salvar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-dist
          path: build

      # Roda um unico comando no shell
      - name: Run a one-line script
        run: echo Hello, world!

